# **Conclusiones y recomendaciones**

Los datos, en la actualidad, han dejado de ser un recurso escaso y de poco interés y se están convirtiendo en uno abundante y de valor estratégico para la gestión de las entidades públicas modernas y, entre estas, sus universidades. Estos, traducidos en información, juegan un rol protagónico en los procesos permanentes de rendición de cuentas a la sociedad; aumentan, si se disponen de manera abierta y accesible, los niveles de transparencia institucional y de confianza ciudadana sobre las actuaciones públicas; favorecen la planeación y la toma de decisiones nacionales, sectoriales e institucionales basadas en información; permiten el monitoreo y la evaluación de políticas públicas materializadas en planes, programas y proyectos de desarrollo y, finalmente, favorecen el estudio, el conocimiento, la predicción y la implementación de acciones preventivas o correctivas que aporten, desde lo público, a la construcción de una mejor sociedad.

Los datos, desde una perspectiva económica, pueden ser clasificados como bienes de naturaleza no rival; su uso analítico para un propósito no impide que sean usados para otros fines. Esta característica, sumada al crecimiento en su volumen y accesibilidad, su variedad, la capacidad de almacenamiento, la facilidad de procesamiento y su utilidad y popularidad, han despertado en la actualidad un amplio interés en los contextos académico, técnico y de gestión pública, principalmente. A la estadística, disciplina académica tradicional encargada del estudio y uso cuantitativo de los datos, se han sumado nuevos actores, profesiones o tendencias interesadas y orientadas a la extracción del conocimiento contenido en los datos institucionales como la inteligencia de negocios, la analítica o minería de datos, el Big Data y la ciencia de los datos, las cuales están aportando nuevas y variadas formas de entendimiento, gestión y uso de la información cuantitativa en el escenario estatal.

La gestión de la información cuantitativa moderna en las entidades públicas está altamente influenciada por el dominio, el uso y el lenguaje derivado de las TIC. Sistemas de información; datos estructurados, semiestructurados y no estructurados; bases de datos relacionales y no relacionales; _scripts_ o programas computacionales; transferencia de datos a sistemas de información locales, sectoriales y nacionales; procesamiento computacional de datos de manera local, distribuida o en paralelo; rutinas tecnológicas de extracción, transformación y almacenamiento de datos en bodegas de datos, _data lakes_ o _data marts_; _software_ especializados para el procesamiento, análisis y visualización de información cuantitativa; disposición de cifras a través de cubos de datos, cuadros de mando, _dashboards_, infografías, presentaciones y boletines electrónicos, así como el uso creciente de redes sociales para comunicar los resultados contenidos en las cifras institucionales, son una muestra del lenguaje técnico y cotidiano que acompaña la gestión moderna de la información cuantitativa.

La importancia y el protagonismo que está adquiriendo la tecnología en la gestión de la información cuantitativa en las entidades públicas exige no olvidar que esta es un medio y no un fin; el fin es la información contenida en los datos bajo custodia estatal. El primer paso que debe orientar una apuesta de aprovechamiento de los datos disponibles en las entidades públicas es un análisis riguroso del qué y el para qué de la información requerida y luego sí el estudio, la adquisición, el dominio y uso de las herramientas tecnológicas que favorezcan la gestión de las cifras cuantitativas institucionales. Infortunadamente, es común observar en las entidades del Estado que primero se adquieren, a través de inversiones importantes, herramientas tecnológicas orientadas a la gestión de los datos institucionales y luego se pregunta qué tipo de información cuantitativa es la que se requiere y se debe gestionar. No toda herramienta tecnológica orientada a la extracción del conocimiento contenido en los datos institucionales es útil para cualquier propósito, y no todo propósito cuantitativo exige la adquisición y el uso de las mismas herramientas tecnológicas. 

Las entidades y las universidades públicas en Colombia, desde finales del siglo pasado, han venido experimentando un proceso de transformación y de regulación orientado al mejoramiento de la gestión administrativa y la calidad de los servicios prestados. Esta transformación, que hace parte de la nueva gestión pública, se ha venido materializando a través de la disposición de un número creciente de políticas, leyes, lineamientos, modelos, directrices, manuales, guías, normas técnicas, etc., de alcance nacional o sectorial. Hoy, se espera que una entidad pública esté siendo gobernada y gestionada de manera correcta si hace uso intensivo de la planeación, obtiene sus resultados a través de una gestión orientada por procesos y proyectos, es transparente, rinde cuentas a la sociedad, hace un uso intensivo de las nuevas tecnologías de la información y las comunicaciones, gestiona sus datos y facilita el acceso de manera abierta a la información disponible, evalúa la calidad de sus servicios a través de la disposición y conservación de certificaciones y sellos de calidad, y posee mecanismos de control y autocontrol, entre otros aspectos.

Los elementos y el lenguaje que hacen parte de las nuevas formas de administrar las entidades públicas en Colombia, sin excepción, están acompañados de una creciente necesidad de gestionar y usar la información cuantitativa disponible a nivel institucional, la cual se materializa a través de la obligación de contar con estadísticas oficiales, indicadores de diversas tipologías, evaluaciones a políticas públicas, transferencia de microdatos a sistemas nacionales y sectoriales, disposición de datos e información cuantitativa de manera abierta, e incursión en el escenario de los grandes datos (_Big Data_), principalmente. Para ello, se han venido expidiendo leyes, lineamientos, directrices, normas y manuales orientados a la organización y el mejoramiento de la información cuantitativa disponible a nivel estatal como las derivadas del Sistema Estadístico Nacional en cabeza del DANE; la Política Nacional de Explotación de Datos –_Big Data_– y los lineamientos metodológicos para el seguimiento y la evaluación de políticas públicas en cabeza del DNP; la estrategia de Gobierno Digital y de datos abiertos liderada por el MinTIC; la expedición del MIPG en cabeza del DAFP, y la disposición e implementación de leyes como las de Transparencia y del derecho al buen uso de los datos personales (_Habeas Data_).

Las universidades públicas colombianas, además de enfrentar demandas de información cuantitativa provenientes, en su mayoría, de instancias superiores pertenecientes al Estado, requieren y hacen uso de un número elevado de cifras en la toma de decisiones, la gestión administrativa y la garantía de la calidad esperada en los resultados derivados del cumplimiento de sus funciones misionales. Indicadores estadísticos para procesos de autoevaluación con miras a la acreditación en alta calidad de programas académicos e instituciones; indicadores de procesos administrativos institucionales; carga de datos a sistemas nacionales de información como el SNIES; construcción y disposición de cifras generales de aspirantes, admitidos, matriculados, graduados, docentes, funcionarios administrativos, investigadores, grupos de investigación, productos de investigación (publicaciones, patentes, citaciones, etc.), programas académicos, movilidad entrante y saliente de docentes y estudiantes; cobertura en programas de bienestar universitario; capacidad financiera, entre otros, hacen parte de la cotidianidad y las necesidades cuantitativas sentidas en el contexto universitario actual.

En Colombia, la diversidad de leyes, directrices, normas, lineamientos, manuales y guías expedidas por diversas entidades del orden nacional y sectorial en materia de gestión de la información cuantitativa carecen, al compararse entre sí, de un lenguaje coherente y un propósito común o complementario sobre el alcance y la forma como la información estadística debe ser entendida y gestionada a nivel institucional. Conceptos afines entendidos de diversas maneras; aproximaciones al uso de los datos desde perspectivas únicas; alcances disímiles en el uso y gestión de los datos; presencia de términos y conceptos complejos; incursión en frentes y tendencias modernas en materia de gestión de los datos sin haber avanzado en lo básico; desconocimiento de las misiones, las especificidades y la diversidad de las entidades que conforman el Estado; poca socialización e interacción con las entidades públicas; bajos niveles de seguimiento al cumplimiento de las políticas expedidas en términos de gestión de la información cuantitativa, entre otros, son una muestra de la presencia de un nutrido acervo de lineamientos a nivel estatal cuyo contenido dista de lo que conocen, requieren, están en capacidad de gestionar y usan un buen número de las entidades públicas en materia de gestión de la información cuantitativa disponible. Una mayor interacción entre las entidades nacionales encargadas de generar lineamientos para el uso de los datos disponibles a nivel institucional, desde luego, redundará en una mejor gestión y disposición de las cifras y los análisis que requieren la nación y sus entidades.

La necesidad de conocer las entidades y universidades públicas para administrarlas encuentra en los datos institucionales una fuente y punto de apoyo central. Para que este apoyo sea efectivo, la gestión moderna de los datos a nivel estatal e institucional implica el reconocimiento y el trabajo en al menos cuatro dimensiones: académica, normativa, tecnológica y de gestión. La aproximación académica se orienta a la definición del alcance que tendrá el uso de los datos institucionales, el estudio y conocimiento de las disciplinas o tendencias bajo las cuales estos serán analizados, el conocimiento de las bases conceptuales y metodológicas que guiarán la gestión de los datos, así como la definición del lenguaje que orientará y acompañará la actividad estadística, entre otros propósitos. La dimensión normativa tiene entre sus haberes el estudio, conocimiento y alcance a nivel institucional de las políticas, normas, lineamientos, modelos, guías, etc., del orden internacional, nacional, sectorial e institucional que regulan y fomentan el ejercicio estadístico en el ámbito estatal. La dimensión tecnológica se orienta al estudio y la definición de la arquitectura, las herramientas y las competencias requeridas en materia tecnológica para la gestión moderna de la información cuantitativa institucional y, finalmente, la perspectiva de la gestión concentra su actuar en la consolidación de las instancias o áreas de las entidades encargadas de la gestión estadística, la disposición de los recursos humanos y financieros requeridos para su funcionamiento, así como el estudio y la definición de los procesos bajo los cuales se garantizará la producción regular de las cifras institucionales requeridas.

El contexto moderno de uso de los datos institucionales está permeado por tendencias y modas provenientes del mundo tecnológico, principalmente. Analítica de datos, minería de datos, ciencia de los datos, Big Data, aprendizaje profundo, aprendizaje automático, inteligencia artificial son algunos de los términos que con frecuencia ocupan las portadas de los diarios, convocan y reúnen a expertos en congresos y eventos, orientan la definición de políticas estatales y fomentan su estudio a nivel técnico y académico. Este auge, derivado en buena medida de su aplicación y utilidad en el escenario de las empresas de base tecnológica, se aspira a que incursione paulatinamente en el contexto de las entidades y universidades públicas con el fin de mejorar la calidad de los servicios prestados y la eficiencia institucional. Aunque no existe claridad sobre el alcance y la forma como estas nuevas aproximaciones impactarán la gestión pública y el uso de los datos disponibles a nivel institucional, desde ya, su reconocimiento y estudio favorecerá su implementación en los ámbitos estatal e institucional.

Aunque las tendencias y el lenguaje de moda asociado a la gestión de la información cuantitativa a nivel institucional, como se mencionó en el ítem anterior, está fuertemente orientado hacia la incursión y el uso de procedimientos de moda, estas aproximaciones no son las que más demandan y usan las entidades y universidades en materia de aprovechamiento de los datos institucionales disponibles; en el contexto actual de la gestión pública, estas son más una expectativa de futuro que una realidad de presente. La disposición de estadísticas e indicadores institucionales, por el contrario, es el uso más frecuente y el fin más buscado a través de la gestión de los datos institucionales disponibles. Estas cifras, de naturaleza descriptiva, han acompañado la historia de desarrollo de los Estados y sus instituciones, y su estudio y gestión, como se presenta en el último capítulo de este libro, aún guardan páginas gloriosas por escribir en la historia de la información cuantitativa y su aprovechamiento a nivel estatal e institucional.

Las estadísticas son el instrumento cuantitativo que, por excelencia, permite describir de manera numérica el comportamiento del Estado y sus instituciones. La gestión moderna de las estadísticas en las entidades y universidades implica el reconocimiento de un número importante de rasgos que las definen, entre los que se encuentran: ser construidas a partir de la disposición de información poblacional o muestral; estar conformadas por cifras agregadas; disponer de información temporal, geográfica y temática; representar el comportamiento de poblaciones minoritarias, con limitaciones o en situación de desigualdad (inclusivas/incluyentes); ser susceptibles de ser representadas de manera tabular y gráfica; hacer uso de normas, conceptos, estándares y nomenclaturas que favorezcan su entendimiento y comparación; estar disponibles a través de diversos medios de difusión y comunicación; hacer uso intensivo de las TIC; ser construidas a partir de un proceso estadístico y, finalmente, servir de base para la construcción de nuevas estadísticas, indicadores o sistemas de medición de mayor especificidad y complejidad.

La aproximación y el uso descriptivo de los datos institucionales, además de las estadísticas, implica el estudio de los indicadores los cuales juegan un papel protagónico en el contexto de la gestión pública moderna. Aunque este trabajo hace una aproximación superficial y ligera a uno de los tipos de indicadores existentes –_desarrollo o cumplimiento_–, este documento es limitado en el análisis, uso y alcance de estas medidas. En un trabajo futuro esperamos avanzar en dirección de los indicadores con el fin de abarcar una de las dimensiones de mayor diversidad y complejidad en el mundo de la gestión de la información cuantitativa estatal. Así mismo, esperamos abordar temas relacionados y complementarios a la gestión cuantitativa como el de la dimensión o perspectiva cualitativa tanto de los indicadores como de las evaluaciones de políticas públicas institucionales.

El valor y el volumen creciente de los datos, así como la importancia de una adecuada gestión de los mismos al interior de las entidades y universidades del Estado exige, en tiempos modernos, la creación de áreas, instancias, oficinas de estadística o de análisis e inteligencia institucional orientadas a la extracción del conocimiento contenido en los datos disponibles. Para que un área u oficina de estadística cumpla de manera adecuada su función, esta, además de estar constituida de manera formal dentro de las estructuras administrativas institucionales, debe contar con el apoyo directivo, ubicarse cerca de los tomadores de decisiones institucionales, contar con los recursos financieros y humanos adecuados, fomentar la aproximación y el estudio multidisciplinario de los datos, disponer y dominar diversas herramientas tecnológicas orientadas a la gestión de los datos institucionales, ejercer su función a través de actividades recurrentes y debidamente planeadas y finalmente, tener un amplio conocimiento sobre el funcionamiento de las instituciones así como de las necesidades existentes en materia de uso y disposición de la información cuantitativa requerida.

Este libro es una invitación al fomento, uso y fortalecimiento de una cultura basada en el uso de los datos y de la información cuantitativa disponible en el escenario estatal. En especial, se convierte en una oportunidad para que las universidades públicas pongan a disposición de la sociedad el acervo estadístico derivado del ejercicio de sus funciones misionales a través del cual se da fe de la importancia de contar en el país con un sistema de educación superior público robusto que, además de promover la movilidad social y reducir los niveles históricos de inequidad social, económica y demográfica que ha sufrido nuestra nación, posibilite y brinde a la sociedad acceso a conocimiento de calidad, a la ciencia y a los demás bienes culturales derivados de la educación superior.
